#!/bin/bash

set -eu

project_dir="$(cd "$(dirname "$0")/.." && pwd)"

pushd "${project_dir}" > /dev/null
  docker run --cap-add=NET_ADMIN \
    -v "$PWD:/build" \
    -v /dev/net/tun:/dev/net/tun \
    -w /build \
    -p 127.0.0.1:5910:5910/tcp \
    -e "PXESERVER_TEST_INTEGRATION=true" \
    -it ljfranklin/pxeserver:integration \
    /bin/bash -c "go test -v ./integration"
popd > /dev/null
